# Generated by Django 4.2.1 on 2023-05-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
